[package]
name = "ww-agent-provider"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[features]
test-support = ["dep:async-stream"]

[dependencies]
async-stream = { workspace = true, optional = true }
async-trait.workspace = true
futures-core.workspace = true
futures-util.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio-util.workspace = true

[dev-dependencies]
tokio.workspace = true
